default: &default
  adapter: 'postgresql'
  encoding: utf-8
  pool: 10
  username: 'mlab'
  password: 'mlab'
  host: localhost

production:
  <<: *default
  database: 'mlab_production'
  pool: 10

development:
  <<: *default
  database: 'mlab_development'
  pool: 5

test: &test
  <<: *default
  database: 'mlab_test'