#!/usr/bin/env ruby

# What it does is check if new threads born or have new content.
# The threads will only by check if the average of
# message/time is less that last check time.

require 'thor'
require_relative '../config/setup'
require 'meta/monitor'

class CLI < Thor
  desc 'start', 'Start to looking for threads to archive'
  def start
    # driver = Meta.driver
    # scalper = Meta::Scalper.new driver
    Monitor(Meta.driver, Logger.new(STDOUT)).loop
  end

  desc 'enqueue', 'Add a page to archive'
  method_option :url, type: :string, aliases: '-u'
  def enqueue
    Resque.enqueue(Archive, opts[:url])
  end
end

CLI.start
